// Package arch derives the set of architectures a release line publishes.
//
// Nothing here hardcodes an architecture. Every existing third-party feed carries
// a hand-maintained matrix — meshtastic's is 36 entries with 19 lines of `exclude:`
// and inline ternaries for the renames — and every one of them is wrong the day
// upstream adds or renames one. Deriving the set means a rename is simply an
// architecture that is no longer in the source, and a new one is a line in a
// lockfile diff that a human approves in a pull request.
package arch

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"owfeed.org/owfeed/internal/netx"
)

// DownloadsBase is OpenWrt's release server. Mirrors are not used for derivation:
// the point of this step is to learn what upstream publishes, and a mirror that is
// mid-sync would answer with a subset.
const DownloadsBase = "https://downloads.openwrt.org"

// PackagesURL is the directory whose subdirectories are exactly the architectures
// a point release publishes packages for.
//
// This is the authoritative source, and it is not the one the design first reached
// for: `.overview.json` carries no arch_packages field on 25.12 at all, only a
// target per profile. Per-target profiles.json does carry it, but that is one
// request per target for something a single directory listing answers.
func PackagesURL(point string) string {
	return fmt.Sprintf("%s/releases/%s/packages/", DownloadsBase, point)
}

// VersionsURL lists every published release.
const VersionsURL = DownloadsBase + "/.versions.json"

// archRE is the shape of an architecture directory name: x86_64,
// aarch64_cortex-a53, arm_arm1176jzf-s_vfp. It exists to notice when the listing
// stops being a listing rather than to define what an architecture is.
var archRE = regexp.MustCompile(`^[a-z0-9]+(_[a-z0-9.+-]+)*$`)

// minPlausibleArches guards against a changed page format silently deriving a short
// or empty set, which would publish a feed covering almost nothing while reporting
// success. OpenWrt has published far more than this for every apk-era release.
const minPlausibleArches = 10

// Result is a derived architecture set.
type Result struct {
	// Arches is sorted and deduplicated.
	Arches []string
	// Source is the URL it came from, recorded in the lockfile so the derivation is
	// auditable. The listing's bytes are deliberately not hashed: it carries file
	// sizes and timestamps, so its hash changes whenever any package is republished
	// and would churn the lockfile without meaning anything.
	Source string
	// FromCache reports that the answer came from disk rather than from upstream.
	FromCache bool
}

// Derive returns the architectures published for a point release.
//
// There is no conditional request here, and it is not an oversight: the listing is
// generated by nginx autoindex on each request and carries neither ETag nor
// Last-Modified, so there is nothing to revalidate against. The saved copy exists
// for Cached, not to skip a fetch. That costs little — this runs once per
// `owfeed lock`, not once per build, because builds read the lockfile.
func Derive(ctx context.Context, hc *http.Client, cacheRoot, point string) (*Result, error) {
	url := PackagesURL(point)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	resp, err := hc.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, netx.Status(url, resp)
	}

	body, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if err != nil {
		return nil, err
	}
	arches, err := parseListing(string(body))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", url, err)
	}

	// A cache write failure is not worth failing a run over; the next run just pays
	// for the request again.
	_ = writeCache(cacheRoot, point, &cacheEntry{Arches: arches})

	return &Result{Arches: arches, Source: url}, nil
}

// Cached returns a previously derived set without touching the network, for runs
// started with --no-network.
//
// It is a separate call rather than a silent fallback inside Derive. A set derived
// at some unknown time in the past is a different thing from one derived now, and
// which of the two a feed was published from should never depend on whether the
// network happened to be reachable.
func Cached(cacheRoot, point string) (*Result, error) {
	e, err := readCache(cacheRoot, point)
	if err != nil {
		return nil, fmt.Errorf("no cached architecture set for %s: %w", point, err)
	}
	return &Result{Arches: e.Arches, Source: PackagesURL(point), FromCache: true}, nil
}

// hrefRE matches the directory entries of an nginx autoindex listing.
var hrefRE = regexp.MustCompile(`href="([^"?/]+)/"`)

func parseListing(body string) ([]string, error) {
	seen := map[string]bool{}
	var out []string
	for _, m := range hrefRE.FindAllStringSubmatch(body, -1) {
		name := m[1]
		if name == ".." || !archRE.MatchString(name) {
			continue
		}
		if seen[name] {
			continue
		}
		seen[name] = true
		out = append(out, name)
	}
	sort.Strings(out)

	if len(out) < minPlausibleArches {
		return nil, fmt.Errorf("derived only %d architectures (%s), which is not a plausible release; "+
			"the directory listing format has probably changed and owfeed is reading it wrong",
			len(out), strings.Join(out, ", "))
	}
	return out, nil
}

// Versions is every release the download server lists, release candidates
// included — filtering is the caller's business, because "what exists" and "what
// a feed may pin to" are different questions.
//
// Separate from LatestPoint so that a caller asking about several lines pays for
// one request rather than one per line.
func Versions(ctx context.Context, hc *http.Client) ([]string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, VersionsURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := hc.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, netx.Status(VersionsURL, resp)
	}

	var versions struct {
		Stable string   `json:"stable_version"`
		List   []string `json:"versions_list"`
	}
	if err := json.NewDecoder(io.LimitReader(resp.Body, 1<<20)).Decode(&versions); err != nil {
		return nil, fmt.Errorf("%s: %w", VersionsURL, err)
	}
	return versions.List, nil
}

// LatestPoint resolves a release line such as "25.12" to its newest point release.
//
// Release candidates are never returned: a feed pinned to an -rc is pinned to
// something that will stop existing.
func LatestPoint(ctx context.Context, hc *http.Client, line string) (string, error) {
	list, err := Versions(ctx, hc)
	if err != nil {
		return "", err
	}
	return pickLatest(line, list)
}

// LatestPointIn answers the same question against a list already fetched.
func LatestPointIn(line string, published []string) (string, error) {
	return pickLatest(line, published)
}

func pickLatest(line string, list []string) (string, error) {
	best, bestPatch := "", -1
	for _, v := range list {
		patch, ok := patchOf(line, v)
		if !ok {
			continue
		}
		if patch > bestPatch {
			best, bestPatch = v, patch
		}
	}
	if best == "" {
		return "", fmt.Errorf("no released point version found for line %q", line)
	}
	return best, nil
}

// patchOf reports the patch number of v if it is a final release on line.
func patchOf(line, v string) (int, bool) {
	rest, ok := strings.CutPrefix(v, line+".")
	if !ok {
		return 0, false
	}
	// Anything beyond the number — "-rc1", "-beta" — is not a release.
	n, err := strconv.Atoi(rest)
	if err != nil {
		return 0, false
	}
	return n, true
}

type cacheEntry struct {
	Arches []string `json:"arches"`
}

func cachePath(cacheRoot, point string) string {
	return filepath.Join(cacheRoot, "arches", point+".json")
}

func readCache(cacheRoot, point string) (*cacheEntry, error) {
	if cacheRoot == "" {
		return nil, errors.New("no cache directory")
	}
	b, err := os.ReadFile(cachePath(cacheRoot, point))
	if err != nil {
		return nil, err
	}
	var e cacheEntry
	if err := json.Unmarshal(b, &e); err != nil {
		return nil, err
	}
	if len(e.Arches) < minPlausibleArches {
		return nil, errors.New("cached architecture set is implausibly short")
	}
	return &e, nil
}

func writeCache(cacheRoot, point string, e *cacheEntry) error {
	if cacheRoot == "" {
		return nil
	}
	path := cachePath(cacheRoot, point)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(e, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}
